### ISSUE TITLE
Failure with getAllUsers() on pyral 1.3.1/1.4.0, Python 3.6.2

### ISSUE THREAD

**Issue by pgacv2** [RallyTools/RallyRestToolkitForPython#129] opened 2017-11-15 16:46 UTC
This is the same as #125, but including pyral 1.4.0 in the affected versions. The failure is reproducible across retries separated by `time.sleep()`s.

Code to reproduce:
```
import pyral
rally = pyral.Rally(apikey='*****')
users = rally.getAllUsers()
```
Result:
```
"C:\Program Files\Python36\python.exe" C:/Users/me/.PyCharmCE2017.1/config/scratches/scratch_7.py
Retrying the page_urls for the page group startIndexes: 501 -> 1001
Retrying the page_urls for the page group startIndexes: 501 -> 1001
Traceback (most recent call last):
Retrying the page_urls for the page group startIndexes: 501 -> 1001
  File "C:/Users/me/.PyCharmCE2017.1/config/scratches/scratch_7.py", line 4, in <module>
    users = rally.getAllUsers()
  File "C:\Program Files\Python36\lib\site-packages\pyral\restapi.py", line 633, in getAllUsers
    users = [user for user in response]
  File "C:\Program Files\Python36\lib\site-packages\pyral\restapi.py", line 633, in <listcomp>
    users = [user for user in response]
  File "C:\Program Files\Python36\lib\site-packages\pyral\rallyresp.py", line 311, in __next__
    self._page[:]  = self.__retrieveNextPage()
  File "C:\Program Files\Python36\lib\site-packages\pyral\rallyresp.py", line 408, in __retrieveNextPage
    chapter = self.__retrievePages()
  File "C:\Program Files\Python36\lib\site-packages\pyral\rallyresp.py", line 476, in __retrievePages
    raise RallyResponseError("Unable to retrieve %d chunks of data" % num_threads)
pyral.rallyresp.RallyResponseError: Unable to retrieve 2 chunks of data

Process finished with exit code 1
```

**Comment by klehman-rally** [comment] 2017-12-12 19:03
Is the behavior you observe consistent?  ( in terms of time-of-day, day-of-week, etc. when you are making the request).  Internally, pyral has a preferred chunk size of 500 when retrieving information.  It may be necessary to expose an argument to getAllUsers to be able to specify a smaller chunk size.  Do you have a ballpark estimate on the total number of users in your subscription?

**Comment by pgacv2** [comment] 2017-12-14 14:34
The behavior is reproducible at different times and days. The users page (https://rally1.rallydev.com/#/.../users) shows about 5k users, but I am not a subscription admin, so I assume those 5k are only for the workspaces I have access to. Does getAllUsers() fetch users for the entire subscription regardless of my account's permissions?

**Comment by klehman-rally** [comment] 2018-01-09 18:14
Yes, getAllUsers will get all users for a subscription (even though there is a keyword arg for workspace in the method signature).  What do you (or intend to do) with the results from the call to getAllUsers?  It is possible that your intended use would utilize less attributes than what are requested internally in the field fetch list or don't utilize reference attribute sub fields.  In that case there may be another approach that might be more successful for you.

**Comment by macaroni1957** [comment] 2018-02-26 20:57
Hi. I received the same error, tried the URL strings individually and they both seemed to work (I am a workspace admin). I then modified line 182 in rallyresp.py to 'self.threads = 1   # TBD was 2', blew away the pycache file, and things worked.

**Comment by abhi19935** [comment] 2019-06-14 09:26
Hi, i am still getting above error can anyone pls post the resolution.
Below is my code:
rally = Rally(server='rally1.rallydev.com', 
          apikey="*******************",
          workspace='my_workspace', project='my_project',
          server_ping=False)
all_user = rally.getAllUsers(workspace="my_workspace")
for users in all_user:
    print(users.UserName)
    print(user.Name)

**Comment by klehman-rally** [comment] 2019-06-17 16:14
abhi19935, what is the total population of users for your subscription?  As your example shows that you are only using the UserName and Name you may be able to use an alternate strategy of utilizing rally.get('User', fetch="Name,UserName") and then iterating over the response object.  
Also, refer to macaroni1957 approach where he limits the threads to 1.  I haven't been able to reproduce the behavior others have reported in the subscriptions available to me.

**Comment by Gobmas** [comment] 2020-05-06 22:28
I'm getting the same issue as above, with just a higher thread count:

```
Retrying the page_urls for the page group startIndexes: 501 -> 5001
Retrying the page_urls for the page group startIndexes: 501 -> 5001
Retrying the page_urls for the page group startIndexes: 501 -> 5001
Traceback (most recent call last):
  File "rallyWorkspacesAdmins.py", line 18, in <module>
    workspaceUsers = rally.getAllUsers(workspace=wksp.Name)
  File "/usr/local/lib/python3.7/site-packages/pyral/restapi.py", line 636, in getAllUsers
    users = [user for user in response]
  File "/usr/local/lib/python3.7/site-packages/pyral/restapi.py", line 636, in <listcomp>
    users = [user for user in response]
  File "/usr/local/lib/python3.7/site-packages/pyral/rallyresp.py", line 313, in __next__
    self._page[:]  = self.__retrieveNextPage()
  File "/usr/local/lib/python3.7/site-packages/pyral/rallyresp.py", line 410, in __retrieveNextPage
    chapter = self.__retrievePages()
  File "/usr/local/lib/python3.7/site-packages/pyral/rallyresp.py", line 478, in __retrievePages
    raise RallyResponseError("Unable to retrieve %d chunks of data" % num_threads)
pyral.rallyresp.RallyResponseError: Unable to retrieve 10 chunks of data
```

The code that I'm trying is below.
```
rally = Rally('rally1.rallydev.com', 'christopher.l.garber@ge.com', '', apikey)

workspaces = rally.getWorkspaces()
for wksp in workspaces:
    print(wksp.Name)
    rally.setWorkspace(wksp.Name)
    workspaceUsers = rally.getAllUsers()
    for user in workspaceUsers :
```

**Comment by klehman-rally** [comment] 2020-05-07 17:04
Take a look at closed issue https://github.com/RallyTools/RallyRestToolkitForPython/issues/162 . You might get some ideas on how to approach this.  I'm unable to reproduce this issue on subscriptions that are available to me (that have 2000 or fewer total (enabled/disabled) users).  I'm going to also close this issue as the context is identical.

**Closed by klehman-rally** 2020-05-07 17:04 UTC
